apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: xjiangazureci0603
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xjiangazureci0603 
  name: xjiangazureci0603
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: xjiangazureci0603
    weight: 100 
