apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xjiangazureci0603
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xjiangazureci0603 
  name: xjiangazureci0603
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xjiangazureci0603 
