apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xjiangazureci0603
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/quay_xjiang/xjiangazureci0603:azure-5d9758e24a7cc382c48a6dee530bf2821f1080bf
          name: container-image
